spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/whitebox?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: kkkkkkk
  thymeleaf:
    cache: false
mybatis:
  type-aliases-package: com.oracle.pojo
  mapper-locations: classpath:mapper/*.xml

